### PR TITLE
#4 nodes publish diagnostics

### PR DESCRIPTION
**Pull request by abarnes6**
Diagnostics should be working for the nodes, and can be viewable on the website I think.

### CODE REVIEW

**Review by BigBroccoli — APPROVED** [review]
Looks good to me

**Review by submergedcastle — APPROVED** [review]

**Review by Kurosaki077 — APPROVED** [review]
Very cool, very awesome.

**Review by afb29 — APPROVED** [review]
Very nice

**Comment by abarnes6** [comment]
DOESN'T WORK!!!

**Comment by abarnes6** [comment]
WORKS!!

**Pull request merged**
